project:
  type: default

format:
  revealjs:
    theme: [default, theme/custom.scss]
    width: 1280
    height: 720
    slide-number: true
    transition: slide
    chalkboard: true
    logo: images/assetlife-horizontal-color.png
    footer: "AssetLife presentation"
    slide-level: 2
    controls: true
    progress: true
    background-transition: fade
    self-contained: false
    incremental: true